import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import BackToPortFolio from "../../components/backtoportfolio";

export default function SMM() {
  return (
    <div>
      <Head>
        <title>fauzaanu.com | Design - Code - Automation</title>
        <meta
          name="description"
          content="I'm Fauzaan. A designer and developer focused on Automation, Marketing, and Creating Innovative Experiences."
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-8">
        <div className="grid lg:grid-cols-3">
          <div className="about col-start-1 lg:col-start-2">
            <p>
              My ads are fast, effective, and affordable. They can be made to
              fit in with any requirement your business have. Note that, I do
              not provide a photography service, so the product images must be
              provided by you.
            </p>
          </div>
        </div>

        <div className="text-3xl text-yellow-400 font-bold pt-10 col-start-1  pb-10 mx-auto">
          SOCIAL MEDIA POSTS
        </div>

        <BackToPortFolio link="/portfolio" text="" />

        <div className="col-start-class1 col-span-3 p-1 grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-5">
          <Image
            src="/img/1.jpg"
            alt=""
            className="rounded w-auto h-auto"
            width={10000}
            height={10000}
          />

          <Image
            src="/img/3.png"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/4.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/5.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/6.png"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/7.png"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/8.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/9.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/10.png"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/11.png"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/12.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/13.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/14.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/15.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/16.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/17.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/18.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/19.png"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/20.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/21.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/22.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/23.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/24.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/25.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/26.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />

          <Image
            src="/img/28.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/29.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/30.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/31.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/32.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/33.png"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/34.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/35.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/36.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/37.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/38.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/39.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/40.png"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/41.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/42.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/43.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/44.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/45.png"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/46.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
          <Image
            src="/img/47.jpg"
            alt=""
            className="rounded"
            width={1000}
            height={1000}
          />
        </div>
      </main>
    </div>
  );
}
